In [115]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [116]:
racialData_NC = pd.read_csv('./data_sets/NC_censusData.csv')
racialData_NC.head()

SUMLEV  STATE  COUNTY          STNAME          CTYNAME  YEAR  AGEGRP  \
0      50     37       1  North Carolina  Alamance County     1       0   
1      50     37       1  North Carolina  Alamance County     1       1   
2      50     37       1  North Carolina  Alamance County     1       2   
3      50     37       1  North Carolina  Alamance County     1       3   
4      50     37       1  North Carolina  Alamance County     1       4   

   TOT_POP  TOT_MALE  TOT_FEMALE     ...       HWAC_MALE  HWAC_FEMALE  \
0   151131     71890       79241     ...            7202         6823   
1     9524      4846        4678     ...             961          941   
2     9889      5126        4763     ...             897          859   
3    10008      5078        4930     ...             726          725   
4    11100      5412        5688     ...             581          596   

   HBAC_MALE  HBAC_FEMALE  HIAC_MALE  HIAC_FEMALE  HAAC_MALE  HAAC_FEMALE  \
0        566          580        962          912        101           94   
1         96          109        116          141         20           19   
2         84           71        122          130         14           14   
3         52           60        119           89          7            8   
4         44           44         80           81          7            5   

   HNAC_MALE  HNAC_FEMALE  
0         26           41  
1          3            7  
2          1            3  
3          2            3  
4          3            4  

[5 rows x 80 columns]

In [117]:
data_condensed = racialData_NC.drop(columns=['SUMLEV', 'STATE', 'COUNTY'])
data_condensed_total = data_condensed[data_condensed.AGEGRP==0]

In [33]:
sum(racialData_NC[(racialData_NC.CTYNAME=='Alamance County') & (racialData_NC.YEAR==1) & (racialData_NC.AGEGRP!=0)].TOT_POP.unique())

151131

In [118]:
data_condensed_total = data_condensed_total.drop(columns = ['AGEGRP'])
data_condensed_total.head()

STNAME          CTYNAME  YEAR  TOT_POP  TOT_MALE  TOT_FEMALE  \
0   North Carolina  Alamance County     1   151131     71890       79241   
19  North Carolina  Alamance County     2   151155     71904       79251   
38  North Carolina  Alamance County     3   151431     72037       79394   
57  North Carolina  Alamance County     4   152692     72642       80050   
76  North Carolina  Alamance County     5   153265     72824       80441   

    WA_MALE  WA_FEMALE  BA_MALE  BA_FEMALE     ...       HWAC_MALE  \
0     55289      60153    13318      15608     ...            7202   
19    55307      60169    13315      15604     ...            7200   
38    55390      60256    13332      15627     ...            7239   
57    55756      60680    13464      15783     ...            7399   
76    55717      60761    13622      15957     ...            7576   

    HWAC_FEMALE  HBAC_MALE  HBAC_FEMALE  HIAC_MALE  HIAC_FEMALE  HAAC_MALE  \
0          6823        566          580        962          912        101   
19         6814        565          579        961          912        101   
38         6888        568          581        939          895        100   
57         7079        569          593        953          898        102   
76         7259        628          626        963          915        104   

    HAAC_FEMALE  HNAC_MALE  HNAC_FEMALE  
0            94         26           41  
19           94         26           41  
38           98         38           47  
57          100         36           36  
76          118         43           45  

[5 rows x 76 columns]

In [76]:
NC_almanance = data_condensed_total[(data_condensed_total.CTYNAME=='Alamance County')&(data_condensed_total.YEAR==4)]
NC_almanance.head()

STNAME          CTYNAME  YEAR  TOT_POP  TOT_MALE  TOT_FEMALE  \
57  North Carolina  Alamance County     4   152692     72642       80050   

    WA_MALE  WA_FEMALE  BA_MALE  BA_FEMALE     ...       HWAC_MALE  \
57    55756      60680    13464      15783     ...            7399   

    HWAC_FEMALE  HBAC_MALE  HBAC_FEMALE  HIAC_MALE  HIAC_FEMALE  HAAC_MALE  \
57         7079        569          593        953          898        102   

    HAAC_FEMALE  HNAC_MALE  HNAC_FEMALE  
57          100         36           36  

[1 rows x 76 columns]

In [77]:
sum(np.array(NC_almanance[['WA_MALE', 'WA_FEMALE', 'BA_MALE', 'BA_FEMALE', 'IA_MALE', 'IA_FEMALE',
       'AA_MALE', 'AA_FEMALE', 'NA_MALE', 'NA_FEMALE', 'TOM_MALE',
       'TOM_FEMALE']]).reshape(-1,1))

array([152692])

In [78]:
NC_almanance.columns

Index(['STNAME', 'CTYNAME', 'YEAR', 'TOT_POP', 'TOT_MALE', 'TOT_FEMALE',
       'WA_MALE', 'WA_FEMALE', 'BA_MALE', 'BA_FEMALE', 'IA_MALE', 'IA_FEMALE',
       'AA_MALE', 'AA_FEMALE', 'NA_MALE', 'NA_FEMALE', 'TOM_MALE',
       'TOM_FEMALE', 'WAC_MALE', 'WAC_FEMALE', 'BAC_MALE', 'BAC_FEMALE',
       'IAC_MALE', 'IAC_FEMALE', 'AAC_MALE', 'AAC_FEMALE', 'NAC_MALE',
       'NAC_FEMALE', 'NH_MALE', 'NH_FEMALE', 'NHWA_MALE', 'NHWA_FEMALE',
       'NHBA_MALE', 'NHBA_FEMALE', 'NHIA_MALE', 'NHIA_FEMALE', 'NHAA_MALE',
       'NHAA_FEMALE', 'NHNA_MALE', 'NHNA_FEMALE', 'NHTOM_MALE', 'NHTOM_FEMALE',
       'NHWAC_MALE', 'NHWAC_FEMALE', 'NHBAC_MALE', 'NHBAC_FEMALE',
       'NHIAC_MALE', 'NHIAC_FEMALE', 'NHAAC_MALE', 'NHAAC_FEMALE',
       'NHNAC_MALE', 'NHNAC_FEMALE', 'H_MALE', 'H_FEMALE', 'HWA_MALE',
       'HWA_FEMALE', 'HBA_MALE', 'HBA_FEMALE', 'HIA_MALE', 'HIA_FEMALE',
       'HAA_MALE', 'HAA_FEMALE', 'HNA_MALE', 'HNA_FEMALE', 'HTOM_MALE',
       'HTOM_FEMALE', 'HWAC_MALE', 'HWAC_FEMALE', 'HBAC_MA

In [79]:
sum(np.array(NC_almanance[['WAC_MALE', 'WAC_FEMALE', 'BAC_MALE', 'BAC_FEMALE',
       'IAC_MALE', 'IAC_FEMALE', 'AAC_MALE', 'AAC_FEMALE', 'NAC_MALE',
       'NAC_FEMALE']]).reshape(-1,1))

array([155733])

In [80]:
sum(np.array(NC_almanance[['NHWA_MALE', 'NHWA_FEMALE',
       'NHBA_MALE', 'NHBA_FEMALE', 'NHIA_MALE', 'NHIA_FEMALE', 'NHAA_MALE',
       'NHAA_FEMALE', 'NHNA_MALE', 'NHNA_FEMALE', 'NHTOM_MALE', 'NHTOM_FEMALE']]).reshape(-1,1))

array([135591])

In [81]:
sum(np.array(NC_almanance[['HWA_MALE',
       'HWA_FEMALE', 'HBA_MALE', 'HBA_FEMALE', 'HIA_MALE', 'HIA_FEMALE',
       'HAA_MALE', 'HAA_FEMALE', 'HNA_MALE', 'HNA_FEMALE', 'HTOM_MALE',
       'HTOM_FEMALE']]).reshape(-1,1))

array([17101])

In [82]:
sum(np.array(NC_almanance[['NHWAC_MALE', 'NHWAC_FEMALE', 'NHBAC_MALE', 'NHBAC_FEMALE',
       'NHIAC_MALE', 'NHIAC_FEMALE', 'NHAAC_MALE', 'NHAAC_FEMALE',
       'NHNAC_MALE', 'NHNAC_FEMALE']]).reshape(-1,1))

array([137968])

In [83]:
sum(np.array(NC_almanance[['HBAC_MALE', 'HBAC_FEMALE',
       'HIAC_MALE', 'HIAC_FEMALE', 'HAAC_MALE', 'HAAC_FEMALE', 'HNAC_MALE',
       'HNAC_FEMALE']]).reshape(-1,1))

array([3287])

In [119]:
county_byRace = data_condensed_total[(data_condensed_total.YEAR==4)][['STNAME', 'CTYNAME','TOT_POP', 'TOT_MALE', 'TOT_FEMALE',\
                                                                      'WA_MALE', 'WA_FEMALE', 'BA_MALE', 'BA_FEMALE', 'IA_MALE', 'IA_FEMALE',\
                                                                      'AA_MALE', 'AA_FEMALE', 'NA_MALE', 'NA_FEMALE', 'TOM_MALE', 'TOM_FEMALE']]
county_byRace.head()

STNAME           CTYNAME  TOT_POP  TOT_MALE  TOT_FEMALE  WA_MALE  \
57   North Carolina   Alamance County   152692     72642       80050    55756   
285  North Carolina  Alexander County    37026     18827       18199    17072   
513  North Carolina  Alleghany County    11016      5449        5567     5235   
741  North Carolina      Anson County    26512     13829       12683     6633   
969  North Carolina       Ashe County    26986     13303       13683    12958   

     WA_FEMALE  BA_MALE  BA_FEMALE  IA_MALE  IA_FEMALE  AA_MALE  AA_FEMALE  \
57       60680    13464      15783     1055       1056      940       1073   
285      16953     1246        770       88         63      192        171   
513       5383       83         82       35         17       34         31   
741       6061     6746       6222      133         71      148        156   
969      13367      114         88       38         34       49         66   

     NA_MALE  NA_FEMALE  TOM_MALE  TOM_FEMALE  
57        49         52      1378        1406  
285        4         10       225         232  
513        2          2        60          52  
741       11          5       158         168  
969       10          2       134         126

In [95]:
county_byRace.to_csv('./data_sets/NC_counties_byRace.csv')

In [97]:
byHispanic = data_condensed_total[(data_condensed_total.YEAR==4)][['STNAME', 'CTYNAME','TOT_POP', 'TOT_MALE', 'TOT_FEMALE',\
                                                                      'NHWA_MALE', 'NHWA_FEMALE','NHBA_MALE', 'NHBA_FEMALE', \
                                                                   'NHIA_MALE', 'NHIA_FEMALE', 'NHAA_MALE','NHAA_FEMALE', 'NHNA_MALE', 'NHNA_FEMALE', \
                                                                   'NHTOM_MALE', 'NHTOM_FEMALE',\
                                                                  'HWA_MALE','HWA_FEMALE', 'HBA_MALE', 'HBA_FEMALE', \
                                                                   'HIA_MALE', 'HIA_FEMALE','HAA_MALE', 'HAA_FEMALE', 'HNA_MALE', \
                                                                   'HNA_FEMALE', 'HTOM_MALE','HTOM_FEMALE']]
byHispanic.head()

STNAME           CTYNAME  TOT_POP  TOT_MALE  TOT_FEMALE  \
57   North Carolina   Alamance County   152692     72642       80050   
285  North Carolina  Alexander County    37026     18827       18199   
513  North Carolina  Alleghany County    11016      5449        5567   
741  North Carolina      Anson County    26512     13829       12683   
969  North Carolina       Ashe County    26986     13303       13683   

     NHWA_MALE  NHWA_FEMALE  NHBA_MALE  NHBA_FEMALE  NHIA_MALE     ...       \
57       48605        53836      13041        15351        261     ...        
285      16296        16243       1208          751         56     ...        
513       4681         5048         66           69         10     ...        
741       6173         5889       6713         6194        107     ...        
969      12191        12972         81           74         24     ...        

     HBA_MALE  HBA_FEMALE  HIA_MALE  HIA_FEMALE  HAA_MALE  HAA_FEMALE  \
57        423         432       794         753        39          43   
285        38          19        32          28         1           3   
513        17          13        25           9         4           6   
741        33          28        26          24         9           5   
969        33          14        14           8         2           0   

     HNA_MALE  HNA_FEMALE  HTOM_MALE  HTOM_FEMALE  
57         17          24        297          284  
285         0           1         14           15  
513         0           1         17            9  
741         9           3         18           24  
969         6           1         21            9  

[5 rows x 29 columns]

In [98]:
byHispanic['TOT_NHWA'] = byHispanic['NHWA_MALE'] + byHispanic['NHWA_FEMALE']
byHispanic['TOT_NHBA'] = byHispanic['NHBA_MALE'] + byHispanic['NHBA_FEMALE']
byHispanic['TOT_NHIA'] = byHispanic['NHIA_MALE'] + byHispanic['NHIA_FEMALE']
byHispanic['TOT_NHAA'] = byHispanic['NHAA_MALE'] + byHispanic['NHAA_FEMALE']
byHispanic['TOT_NHNA'] = byHispanic['NHNA_MALE'] + byHispanic['NHNA_FEMALE']
byHispanic['TOT_NHTOM'] = byHispanic['NHTOM_MALE'] + byHispanic['NHTOM_FEMALE']

byHispanic['TOT_HWA'] = byHispanic['HWA_MALE'] + byHispanic['HWA_FEMALE']
byHispanic['TOT_HBA'] = byHispanic['HBA_MALE'] + byHispanic['HBA_FEMALE']
byHispanic['TOT_HIA'] = byHispanic['HIA_MALE'] + byHispanic['HIA_FEMALE']
byHispanic['TOT_HAA'] = byHispanic['HAA_MALE'] + byHispanic['HAA_FEMALE']
byHispanic['TOT_HNA'] = byHispanic['HNA_MALE'] + byHispanic['HNA_FEMALE']
byHispanic['TOT_HTOM'] = byHispanic['HTOM_MALE'] + byHispanic['HTOM_FEMALE']

In [100]:
byHispanic.to_csv('/Users/jincho/Desktop/pikapixels/data_sets/NC_counties_byHisp.csv')

In [103]:
county_byRace.CTYNAME.unique()

array(['Alamance County', 'Alexander County', 'Alleghany County',
       'Anson County', 'Ashe County', 'Avery County', 'Beaufort County',
       'Bertie County', 'Bladen County', 'Brunswick County',
       'Buncombe County', 'Burke County', 'Cabarrus County',
       'Caldwell County', 'Camden County', 'Carteret County',
       'Caswell County', 'Catawba County', 'Chatham County',
       'Cherokee County', 'Chowan County', 'Clay County',
       'Cleveland County', 'Columbus County', 'Craven County',
       'Cumberland County', 'Currituck County', 'Dare County',
       'Davidson County', 'Davie County', 'Duplin County',
       'Durham County', 'Edgecombe County', 'Forsyth County',
       'Franklin County', 'Gaston County', 'Gates County',
       'Graham County', 'Granville County', 'Greene County',
       'Guilford County', 'Halifax County', 'Harnett County',
       'Haywood County', 'Henderson County', 'Hertford County',
       'Hoke County', 'Hyde County', 'Iredell County', 'Jackson C

In [121]:
county_byRace['CTYNAME'] = county_byRace['CTYNAME'].map(lambda x: x.rstrip(' County'))

In [122]:
county_byRace.CTYNAME.unique()

array(['Alamance', 'Alexander', 'Allegha', 'Ans', 'Ashe', 'Aver',
       'Beaufor', 'Bertie', 'Blade', 'Brunswick', 'Buncombe', 'Burke',
       'Cabarrus', 'Caldwell', 'Camde', 'Cartere', 'Caswell', 'Catawba',
       'Chatham', 'Cherokee', 'Chowa', 'Cla', 'Cleveland', 'Columbus',
       'Crave', 'Cumberland', 'Currituck', 'Dare', 'Davids', 'Davie',
       'Dupli', 'Durham', 'Edgecombe', 'Forsyth', 'Frankli', 'Gas',
       'Gates', 'Graham', 'Granville', 'Greene', 'Guilford', 'Halifax',
       'Harne', 'Haywood', 'Henders', 'Hertford', 'Hoke', 'Hyde',
       'Iredell', 'Jacks', 'Johns', 'Jones', 'Lee', 'Lenoir', 'Lincol',
       'McDowell', 'Mac', 'Madis', 'Marti', 'Mecklenburg', 'Mitchell',
       'Montgomer', 'Moore', 'Nash', 'New Hanover', 'Northamp', 'Onslow',
       'Orange', 'Pamlic', 'Pasquotank', 'Pender', 'Perquimans', 'Pers',
       'Pi', 'Polk', 'Randolph', 'Richmond', 'Robes', 'Rockingham',
       'Rowa', 'Rutherford', 'Samps', 'Scotland', 'Stanl', 'Stokes',
       'Surr', '

In [123]:
county_byRace.to_csv('./data_sets/NC_counties_byRace.csv')

In [109]:
byHispanic['CTYNAME'] = byHispanic['CTYNAME'].map(lambda x: x.rstrip(' County'))

In [110]:
byHispanic.to_csv('./data_sets/NC_counties_byHisp.csv')