In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
racialData_NC = pd.read_csv('./data_sets/NC_censusData.csv')
racialData_NC.head()

SUMLEV  STATE  COUNTY          STNAME          CTYNAME  YEAR  AGEGRP  \
0      50     37       1  North Carolina  Alamance County     1       0   
1      50     37       1  North Carolina  Alamance County     1       1   
2      50     37       1  North Carolina  Alamance County     1       2   
3      50     37       1  North Carolina  Alamance County     1       3   
4      50     37       1  North Carolina  Alamance County     1       4   

   TOT_POP  TOT_MALE  TOT_FEMALE  ...  HWAC_MALE  HWAC_FEMALE  HBAC_MALE  \
0   151131     71890       79241  ...       7202         6823        566   
1     9524      4846        4678  ...        961          941         96   
2     9889      5126        4763  ...        897          859         84   
3    10008      5078        4930  ...        726          725         52   
4    11100      5412        5688  ...        581          596         44   

   HBAC_FEMALE  HIAC_MALE  HIAC_FEMALE  HAAC_MALE  HAAC_FEMALE  HNAC_MALE  \
0          580        962          912        101           94         26   
1          109        116          141         20           19          3   
2           71        122          130         14           14          1   
3           60        119           89          7            8          2   
4           44         80           81          7            5          3   

   HNAC_FEMALE  
0           41  
1            7  
2            3  
3            3  
4            4  

[5 rows x 80 columns]

In [34]:
data_condensed = racialData_NC.drop(columns=['SUMLEV', 'STATE', 'COUNTY'])
data_condensed_total = data_condensed[data_condensed.AGEGRP==0]

In [33]:
sum(racialData_NC[(racialData_NC.CTYNAME=='Alamance County') & (racialData_NC.YEAR==1) & (racialData_NC.AGEGRP!=0)].TOT_POP.unique())

151131

In [37]:
data_condensed_total = data_condensed_total.drop(columns = ['AGEGRP'])
data_condensed_total.head()

STNAME          CTYNAME  YEAR  TOT_POP  TOT_MALE  TOT_FEMALE  \
0   North Carolina  Alamance County     1   151131     71890       79241   
19  North Carolina  Alamance County     2   151155     71904       79251   
38  North Carolina  Alamance County     3   151431     72037       79394   
57  North Carolina  Alamance County     4   152692     72642       80050   
76  North Carolina  Alamance County     5   153265     72824       80441   

    WA_MALE  WA_FEMALE  BA_MALE  BA_FEMALE     ...       HWAC_MALE  \
0     55289      60153    13318      15608     ...            7202   
19    55307      60169    13315      15604     ...            7200   
38    55390      60256    13332      15627     ...            7239   
57    55756      60680    13464      15783     ...            7399   
76    55717      60761    13622      15957     ...            7576   

    HWAC_FEMALE  HBAC_MALE  HBAC_FEMALE  HIAC_MALE  HIAC_FEMALE  HAAC_MALE  \
0          6823        566          580        962          912        101   
19         6814        565          579        961          912        101   
38         6888        568          581        939          895        100   
57         7079        569          593        953          898        102   
76         7259        628          626        963          915        104   

    HAAC_FEMALE  HNAC_MALE  HNAC_FEMALE  
0            94         26           41  
19           94         26           41  
38           98         38           47  
57          100         36           36  
76          118         43           45  

[5 rows x 76 columns]

In [76]:
NC_almanance = data_condensed_total[(data_condensed_total.CTYNAME=='Alamance County')&(data_condensed_total.YEAR==4)]
NC_almanance.head()

STNAME          CTYNAME  YEAR  TOT_POP  TOT_MALE  TOT_FEMALE  \
57  North Carolina  Alamance County     4   152692     72642       80050   

    WA_MALE  WA_FEMALE  BA_MALE  BA_FEMALE     ...       HWAC_MALE  \
57    55756      60680    13464      15783     ...            7399   

    HWAC_FEMALE  HBAC_MALE  HBAC_FEMALE  HIAC_MALE  HIAC_FEMALE  HAAC_MALE  \
57         7079        569          593        953          898        102   

    HAAC_FEMALE  HNAC_MALE  HNAC_FEMALE  
57          100         36           36  

[1 rows x 76 columns]

In [77]:
sum(np.array(NC_almanance[['WA_MALE', 'WA_FEMALE', 'BA_MALE', 'BA_FEMALE', 'IA_MALE', 'IA_FEMALE',
       'AA_MALE', 'AA_FEMALE', 'NA_MALE', 'NA_FEMALE', 'TOM_MALE',
       'TOM_FEMALE']]).reshape(-1,1))

array([152692])

In [78]:
NC_almanance.columns

Index(['STNAME', 'CTYNAME', 'YEAR', 'TOT_POP', 'TOT_MALE', 'TOT_FEMALE',
       'WA_MALE', 'WA_FEMALE', 'BA_MALE', 'BA_FEMALE', 'IA_MALE', 'IA_FEMALE',
       'AA_MALE', 'AA_FEMALE', 'NA_MALE', 'NA_FEMALE', 'TOM_MALE',
       'TOM_FEMALE', 'WAC_MALE', 'WAC_FEMALE', 'BAC_MALE', 'BAC_FEMALE',
       'IAC_MALE', 'IAC_FEMALE', 'AAC_MALE', 'AAC_FEMALE', 'NAC_MALE',
       'NAC_FEMALE', 'NH_MALE', 'NH_FEMALE', 'NHWA_MALE', 'NHWA_FEMALE',
       'NHBA_MALE', 'NHBA_FEMALE', 'NHIA_MALE', 'NHIA_FEMALE', 'NHAA_MALE',
       'NHAA_FEMALE', 'NHNA_MALE', 'NHNA_FEMALE', 'NHTOM_MALE', 'NHTOM_FEMALE',
       'NHWAC_MALE', 'NHWAC_FEMALE', 'NHBAC_MALE', 'NHBAC_FEMALE',
       'NHIAC_MALE', 'NHIAC_FEMALE', 'NHAAC_MALE', 'NHAAC_FEMALE',
       'NHNAC_MALE', 'NHNAC_FEMALE', 'H_MALE', 'H_FEMALE', 'HWA_MALE',
       'HWA_FEMALE', 'HBA_MALE', 'HBA_FEMALE', 'HIA_MALE', 'HIA_FEMALE',
       'HAA_MALE', 'HAA_FEMALE', 'HNA_MALE', 'HNA_FEMALE', 'HTOM_MALE',
       'HTOM_FEMALE', 'HWAC_MALE', 'HWAC_FEMALE', 'HBAC_MA

In [79]:
sum(np.array(NC_almanance[['WAC_MALE', 'WAC_FEMALE', 'BAC_MALE', 'BAC_FEMALE',
       'IAC_MALE', 'IAC_FEMALE', 'AAC_MALE', 'AAC_FEMALE', 'NAC_MALE',
       'NAC_FEMALE']]).reshape(-1,1))

array([155733])

In [80]:
sum(np.array(NC_almanance[['NHWA_MALE', 'NHWA_FEMALE',
       'NHBA_MALE', 'NHBA_FEMALE', 'NHIA_MALE', 'NHIA_FEMALE', 'NHAA_MALE',
       'NHAA_FEMALE', 'NHNA_MALE', 'NHNA_FEMALE', 'NHTOM_MALE', 'NHTOM_FEMALE']]).reshape(-1,1))

array([135591])

In [81]:
sum(np.array(NC_almanance[['HWA_MALE',
       'HWA_FEMALE', 'HBA_MALE', 'HBA_FEMALE', 'HIA_MALE', 'HIA_FEMALE',
       'HAA_MALE', 'HAA_FEMALE', 'HNA_MALE', 'HNA_FEMALE', 'HTOM_MALE',
       'HTOM_FEMALE']]).reshape(-1,1))

array([17101])

In [82]:
sum(np.array(NC_almanance[['NHWAC_MALE', 'NHWAC_FEMALE', 'NHBAC_MALE', 'NHBAC_FEMALE',
       'NHIAC_MALE', 'NHIAC_FEMALE', 'NHAAC_MALE', 'NHAAC_FEMALE',
       'NHNAC_MALE', 'NHNAC_FEMALE']]).reshape(-1,1))

array([137968])

In [83]:
sum(np.array(NC_almanance[['HBAC_MALE', 'HBAC_FEMALE',
       'HIAC_MALE', 'HIAC_FEMALE', 'HAAC_MALE', 'HAAC_FEMALE', 'HNAC_MALE',
       'HNAC_FEMALE']]).reshape(-1,1))

array([3287])

In [94]:
county_byRace = data_condensed_total[(data_condensed_total.YEAR==4)][['STNAME', 'CTYNAME','TOT_POP', 'TOT_MALE', 'TOT_FEMALE',\
                                                                      'WA_MALE', 'WA_FEMALE', 'BA_MALE', 'BA_FEMALE', 'IA_MALE', 'IA_FEMALE',\
                                                                      'AA_MALE', 'AA_FEMALE', 'NA_MALE', 'NA_FEMALE', 'TOM_MALE']]


STNAME              CTYNAME  TOT_POP  TOT_MALE  TOT_FEMALE  \
57     North Carolina      Alamance County   152692     72642       80050   
285    North Carolina     Alexander County    37026     18827       18199   
513    North Carolina     Alleghany County    11016      5449        5567   
741    North Carolina         Anson County    26512     13829       12683   
969    North Carolina          Ashe County    26986     13303       13683   
1197   North Carolina         Avery County    17770      9675        8095   
1425   North Carolina      Beaufort County    47675     22935       24740   
1653   North Carolina        Bertie County    20858     10342       10516   
1881   North Carolina        Bladen County    34880     16695       18185   
2109   North Carolina     Brunswick County   110185     53767       56418   
2337   North Carolina      Buncombe County   241172    116052      125120   
2565   North Carolina         Burke County    90542     45231       45311   
2793   North Carolina      Cabarrus County   181175     88381       92794   
3021   North Carolina      Caldwell County    82451     40649       41802   
3249   North Carolina        Camden County    10024      4981        5043   
3477   North Carolina      Carteret County    67418     33299       34119   
3705   North Carolina       Caswell County    23456     11936       11520   
3933   North Carolina       Catawba County   154459     75659       78800   
4161   North Carolina       Chatham County    64109     30824       33285   
4389   North Carolina      Cherokee County    27180     13155       14025   
4617   North Carolina        Chowan County    14807      7040        7767   
4845   North Carolina          Clay County    10686      5270        5416   
5073   North Carolina     Cleveland County    97442     46964       50478   
5301   North Carolina      Columbus County    57705     28516       29189   
5529   North Carolina        Craven County   104831     52405       52426   
5757   North Carolina    Cumberland County   330503    162689      167814   
5985   North Carolina     Currituck County    23906     11835       12071   
6213   North Carolina          Dare County    34156     16954       17202   
6441   North Carolina      Davidson County   162923     79810       83113   
6669   North Carolina         Davie County    41335     20091       21244   
...               ...                  ...      ...       ...         ...   
16017  North Carolina        Pender County    53175     26591       26584   
16245  North Carolina    Perquimans County    13498      6462        7036   
16473  North Carolina        Person County    39520     19168       20352   
16701  North Carolina          Pitt County   170791     80468       90323   
16929  North Carolina          Polk County    20288      9717       10571   
17157  North Carolina      Randolph County   141858     69887       71971   
17385  North Carolina      Richmond County    46651     22918       23733   
17613  North Carolina       Robeson County   135183     65660       69523   
17841  North Carolina    Rockingham County    93284     44956       48328   
18069  North Carolina         Rowan County   137805     68041       69764   
18297  North Carolina    Rutherford County    67416     32586       34830   
18525  North Carolina       Sampson County    63514     31159       32355   
18753  North Carolina      Scotland County    36275     17763       18512   
18981  North Carolina        Stanly County    60530     30125       30405   
19209  North Carolina        Stokes County    47142     22994       24148   
19437  North Carolina         Surry County    73496     35852       37644   
19665  North Carolina         Swain County    14007      6806        7201   
19893  North Carolina  Transylvania County    32807     15814       16993   
20121  North Carolina       Tyrrell County     4337      2393        1944   
20349  North Carolina         Union County   204888    101112      103776   
20577  Nort

In [95]:
county_byRace.to_csv('/Users/jincho/Desktop/pikapixels/data_sets/NC_counties_byRace.csv')

In [97]:
byHispanic = data_condensed_total[(data_condensed_total.YEAR==4)][['STNAME', 'CTYNAME','TOT_POP', 'TOT_MALE', 'TOT_FEMALE',\
                                                                      'NHWA_MALE', 'NHWA_FEMALE','NHBA_MALE', 'NHBA_FEMALE', \
                                                                   'NHIA_MALE', 'NHIA_FEMALE', 'NHAA_MALE','NHAA_FEMALE', 'NHNA_MALE', 'NHNA_FEMALE', \
                                                                   'NHTOM_MALE', 'NHTOM_FEMALE',\
                                                                  'HWA_MALE','HWA_FEMALE', 'HBA_MALE', 'HBA_FEMALE', \
                                                                   'HIA_MALE', 'HIA_FEMALE','HAA_MALE', 'HAA_FEMALE', 'HNA_MALE', \
                                                                   'HNA_FEMALE', 'HTOM_MALE','HTOM_FEMALE']]
byHispanic.head()

STNAME           CTYNAME  TOT_POP  TOT_MALE  TOT_FEMALE  \
57   North Carolina   Alamance County   152692     72642       80050   
285  North Carolina  Alexander County    37026     18827       18199   
513  North Carolina  Alleghany County    11016      5449        5567   
741  North Carolina      Anson County    26512     13829       12683   
969  North Carolina       Ashe County    26986     13303       13683   

     NHWA_MALE  NHWA_FEMALE  NHBA_MALE  NHBA_FEMALE  NHIA_MALE     ...       \
57       48605        53836      13041        15351        261     ...        
285      16296        16243       1208          751         56     ...        
513       4681         5048         66           69         10     ...        
741       6173         5889       6713         6194        107     ...        
969      12191        12972         81           74         24     ...        

     HBA_MALE  HBA_FEMALE  HIA_MALE  HIA_FEMALE  HAA_MALE  HAA_FEMALE  \
57        423         432       794         753        39          43   
285        38          19        32          28         1           3   
513        17          13        25           9         4           6   
741        33          28        26          24         9           5   
969        33          14        14           8         2           0   

     HNA_MALE  HNA_FEMALE  HTOM_MALE  HTOM_FEMALE  
57         17          24        297          284  
285         0           1         14           15  
513         0           1         17            9  
741         9           3         18           24  
969         6           1         21            9  

[5 rows x 29 columns]

In [ ]:
byHispanic['TOT_NHWA'] = byHispanic['NHWA_MALE'] + byHispanic['NHWA_FEMALE']
byHispanic['TOT_NHWA'] = byHispanic['NHBA_MALE'] + byHispanic['NHBA_FEMALE']
byHispanic['TOT_NHWA'] = byHispanic['NHIA_MALE'] + byHispanic['NHIA_FEMALE']
byHispanic['TOT_NHWA'] = byHispanic['NHAA_MALE'] + byHispanic['NHAA_FEMALE']
byHispanic['TOT_NHWA'] = byHispanic['NHNA_MALE'] + byHispanic['NHNA_FEMALE']
byHispanic['TOT_NHWA'] = byHispanic['NHTOM_MALE'] + byHispanic['NHTOM_FEMALE']